[package]
name = "wampproto"
version = "0.1.0"
edition = "2024"

[dependencies]
# serialization deps
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.140"
rmp-serde = "1.3.0"
